### ISSUE TITLE
Critical bug - in master ?

### ISSUE THREAD

**Issue by lbarman** [lbarman/vaultage#145]
run `make serve` on fresh machine (no .vaultage), try to `auth` and `push`:

```
{"name":"BadRequestError","message":"Invalid body, check 'errors' property for more info.","stack":"Error\n    at BadRequestError.HttpError [as constructor] (/home/jwhite/d/git/vaultage/packages/vaultage/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new BadRequestError (/home/jwhite/d/git/vaultage/packages/vaultage/node_modules/routing-controllers/http-error/BadRequestError.js:20:28)\n    at /home/jwhite/d/git/vaultage/packages/vaultage/node_modules/routing-controllers/ActionParameterHandler.js:160:29\n    at process._tickCallback (internal/process/next_tick.js:109:7)","errors":[{"target":{"new_password":null,"new_data":"{\"iv\":\"nM18waspdAdpaow5O92Ygg==\",\"v\":1,\"iter\":10000,\"ks\":128,\"ts\":64,\"mode\":\"ccm\",\"adata\":\"\",\"cipher\":\"aes\",\"salt\":\"vYGqoKf3mSA=\",\"ct\":\"NSxLsDMNHSFhTSQshFos5XxUjSEcaXx7kNbWGGpIwwMweyGH+lPM4wmSIEKZKVM=\"}","new_hash":"be966bb966832f7d644327eb9e162fecb172dbbd0d16e562843cb4fa1450cbe8","force":false},"property":"old_hash","children":[],"constraints":{"isString":"old_hash must be a string"}}]}
```

I tried to `clean`, `cleanall`, is it only me ?

**Comment by hmil** [comment]
weird, I get another error:
When I `push`, the request succeeds but the UI gets stuck waiting for something...
